In [1]:
import pandas as pd
import numpy as np

### Import and join all databases

In [2]:
amsterdam_weekend = pd.read_csv("Data/Amsterdam_Weekends.csv")

In [3]:
amsterdam_weekend['city'] = ('Amsterdam')

In [4]:
barcelona_weekend = pd.read_csv("Data/Barcelona_Weekends.csv")

In [5]:
barcelona_weekend['city'] = ('Barcelona')

In [6]:
athens_weekend = pd.read_csv("Data/Athens_Weekends.csv")

In [7]:
athens_weekend['city'] = ('Athens')

In [8]:
london_weekend = pd.read_csv("Data/London_Weekends.csv")

In [9]:
london_weekend['city'] = ('London')

In [10]:
berlin_weekend = pd.read_csv("Data/Berlin_Weekends.csv")

In [11]:
berlin_weekend['city'] = ('Berlin')

In [12]:
budapest_weekend = pd.read_csv("Data/Budapest_Weekends.csv")

In [13]:
budapest_weekend['city'] = ('Budapest')

In [14]:
lisbon_weekend = pd.read_csv("Data/Lisbon_Weekends.csv")

In [15]:
lisbon_weekend['city'] = ('Lisbon')

In [16]:
paris_weekend = pd.read_csv("Data/Paris_Weekends.csv")

In [17]:
paris_weekend['city'] = ('Paris')

In [18]:
rome_weekend = pd.read_csv("Data/Rome_Weekends.csv")

In [19]:
rome_weekend['city'] = ('Rome')

In [20]:
vienna_weekend = pd.read_csv("Data/Vienna_Weekends.csv")

In [21]:
vienna_weekend['city'] = ('Vienna')

In [22]:
weekend_data = pd.concat((amsterdam_weekend, berlin_weekend, barcelona_weekend, london_weekend, budapest_weekend, lisbon_weekend, paris_weekend, rome_weekend, vienna_weekend, athens_weekend))

In [23]:
weekend_data

,Unnamed: 0,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,...,bedrooms,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat,city
0,0,319.640053,Private room,False,True,2.0,False,0,1,9.0,...,1,4.763360,0.852117,110.906123,5.871971,136.982208,11.941560,4.84639,52.34137,Amsterdam
1,1,347.995219,Private room,False,True,2.0,False,0,1,9.0,...,1,5.748310,3.651591,75.275937,3.985516,95.386468,8.315410,4.97512,52.36103,Amsterdam
2,2,482.975183,Private room,False,True,4.0,False,0,1,9.0,...,2,0.384872,0.439852,493.272517,26.116521,875.114817,76.289005,4.89417,52.37663,Amsterdam
3,3,485.552926,Private room,False,True,2.0,True,0,0,10.0,...,1,0.544723,0.318688,552.849514,29.270850,815.303994,71.074937,4.90051,52.37508,Amsterdam
4,4,2771.541724,Entire home/apt,False,False,4.0,True,0,0,10.0,...,3,1.686798,1.458399,208.809162,11.055489,272.315202,23.739349,4.88467,52.38749,Amsterdam
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2622,2622,74.051508,Entire home/apt,False,False,3.0,True,0,0,10.0,...,1,3.311976,1.856865,49.097725,1.849891,71.119758,1.062098,23.75000,38.00306,Athens
2623,2623,295.737351,Entire home/apt,False,False,4.0,True,0,1,10.0,...,1,1.800556,0.571033,146.240703,5.510019,203.884287,3.044796,23.71500,37.97400,Athens
2624,2624,169.193635,Entire home/apt,False,False,4.0,True,0,1,10.0,...,2,3.845100,0.786416,42.260382,1.592276,60.948754,0.910205,23.76657,37.99986,Athens
2625,2625,160.991728,Entire home/apt,False,False,4.0,True,1,0,10.0,...,1,4.827460,0.141952,35.700540,1.345116,52.659912,0.786420,23.73300,38.01900,Athens
2626,2626,192.393317,Entire home/apt,False,False,4.0,False,0,1,10.0,...,1,1.776319,0.317120,107.126909,4.036300,149.191222,2.228013,23.72863,37.99064,Athens

In [24]:
weekend_data['weekend'] = ('yes')

In [25]:
weekend_data['weekend'].value_counts()

yes    26207
Name: weekend, dtype: int64

In [26]:
weekday_rome = pd.read_csv('Data/Rome_Weekdays.csv')
weekday_rome['city'] = ('Rome')
weekday_berlin = pd.read_csv('Data/Berlin_Weekdays.csv')
weekday_berlin['city'] = ('Berlin')
weekday_london = pd.read_csv('Data/London_Weekdays.csv')
weekday_london['city'] = ('London')
weekday_lisbon = pd.read_csv("Data/Lisbon_Weekdays.csv")
weekday_lisbon['city'] = ('Lisbon')
weekday_amsterdam = pd.read_csv('Data/Amsterdam_Weekdays.csv')
weekday_amsterdam['city'] = ('Amsterdam')
weekday_barcelona = pd.read_csv('Data/Barcelona_Weekdays.csv')
weekday_barcelona['city'] = ('Barcelona')
weekday_budapest = pd.read_csv('Data/Budapest_Weekdays.csv')
weekday_budapest['city'] = ('Budapest')
weekday_athens = pd.read_csv('Data/Athens_Weekdays.csv')
weekday_athens['city'] = ('Athens')
weekday_vienna = pd.read_csv('Data/Vienna_Weekdays.csv')
weekday_vienna['city'] = ('Vienna')
weekday_paris = pd.read_csv('Data/Paris_Weekdays.csv')
weekday_paris['city'] = ('Paris')

In [27]:
weekdays = pd.concat([weekday_rome, weekday_berlin, weekday_london, weekday_lisbon, weekday_amsterdam, weekday_barcelona, weekday_budapest, weekday_athens, weekday_vienna, weekday_paris])

In [28]:
weekdays['weekend'] = ('no')

In [29]:
weekdays

,Unnamed: 0,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,...,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat,city,weekend
0,0,156.874664,Private room,False,True,2.0,True,1,0,10.0,...,2.978468,1.595733,281.163932,6.230648,697.727246,15.191486,12.48654,41.92498,Rome,no
1,1,172.772543,Private room,False,True,2.0,False,1,0,9.0,...,0.935371,0.649269,482.707193,10.696887,1251.524333,27.249208,12.49627,41.90801,Rome,no
2,2,277.745307,Entire home/apt,False,False,4.0,False,0,1,9.0,...,2.203025,0.494697,691.708998,15.328408,1625.897266,35.400361,12.47700,41.90700,Rome,no
3,3,444.906834,Entire home/apt,False,False,6.0,False,1,0,9.0,...,2.703010,1.295153,805.592641,17.852092,2035.819533,44.325522,12.46969,41.90019,Rome,no
4,4,131.391298,Private room,False,True,3.0,False,1,0,9.0,...,1.295968,0.867455,317.076369,7.026475,836.622814,18.215634,12.51544,41.89463,Rome,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3125,3125,231.615248,Entire home/apt,False,False,4.0,False,0,0,10.0,...,3.558773,0.154750,185.488125,9.029499,474.358260,27.873072,2.40050,48.85093,Paris,no
3126,3126,223.692795,Entire home/apt,False,False,2.0,False,1,0,9.0,...,4.205210,0.253034,172.658783,8.404971,406.585538,23.890778,2.40100,48.87700,Paris,no
3127,3127,567.853481,Entire home/apt,False,False,6.0,True,0,0,10.0,...,4.312136,0.304642,178.222781,8.675825,420.726229,24.721678,2.39334,48.88463,Paris,no
3128,3128,200.391462,Entire home/apt,False,False,2.0,True,0,0,9.0,...,2.891206,0.240686,235.168523,11.447924,602.451547,35.399774,2.38200,48.87400,Paris,no
3129,3129,301.286234,Entire home/apt,False,False,2.0,False,0,0,10.0,...,3.469721,0.508493,200.639467,9.767062,478.992836,28.145397,2.39992,48.85886,Paris,no

In [30]:
data = pd.concat((weekdays, weekend_data))

### Drop irrelevant features and transform the boolean data types into dummy variables

In [31]:
data.drop_duplicates(inplace=True)

In [32]:
data.corr()

,Unnamed: 0,realSum,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,guest_satisfaction_overall,bedrooms,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat
Unnamed: 0,1.000000,0.010863,-0.003336,0.039880,-0.001816,-0.059890,-0.001999,0.018735,-0.049342,-0.062290,0.019509,0.186218,0.024200,0.084314,0.035687,0.158729,-0.141629,-0.156467,0.056303
realSum,0.010863,1.000000,-0.035095,-0.171949,0.203077,-0.045478,-0.052926,0.037144,-0.006082,-0.001888,0.221653,-0.044725,-0.061025,0.178228,0.292396,0.134722,0.144094,-0.173833,0.211805
room_shared,-0.003336,-0.035095,1.000000,-0.063533,0.035146,-0.027839,-0.016061,0.044406,-0.040097,-0.027876,-0.021365,0.014144,-0.002868,-0.031458,-0.006137,-0.031297,0.005711,-0.027829,0.023304
room_private,0.039880,-0.171949,-0.063533,1.000000,-0.499993,-0.049501,0.137026,-0.040198,-0.030983,-0.033401,-0.155889,0.213351,0.101981,-0.022286,0.029140,-0.022343,-0.136846,-0.201709,0.140762
person_capacity,-0.001816,0.203077,0.035146,-0.499993,1.000000,0.031431,-0.054326,0.110668,0.003256,0.005181,0.560627,-0.128488,-0.037267,0.028394,-0.050487,0.037330,0.038059,0.146848,-0.168265
host_is_superhost,-0.059890,-0.045478,-0.027839,-0.049501,0.031431,1.000000,0.097520,-0.108506,0.272376,0.280062,0.024250,-0.056113,-0.000722,-0.026335,-0.088949,-0.035060,-0.018348,0.185748,-0.113811
multi,-0.001999,-0.052926,-0.016061,0.137026,-0.054326,0.097520,1.000000,-0.470725,0.041064,0.054254,-0.000659,0.033426,0.043365,0.006319,-0.041412,0.007051,-0.037402,0.041260,-0.034058
biz,0.018735,0.037144,0.044406,-0.040198,0.110668,-0.108506,-0.470725,1.000000,-0.107310,-0.208160,-0.026741,-0.164767,-0.109153,0.114732,0.093720,0.137747,0.083999,-0.088943,-0.126433
cleanliness_rating,-0.049342,-0.006082,-0.040097,-0.030983,0.003256,0.272376,0.041064,-0.107310,1.000000,0.714045,0.033489,-0.030202,0.010441,-0.025322,-0.075372,-0.031929,-0.005995,0.120379,-0.092502
guest_satisfaction_overall,-0.062290,-0.001888,-0.027876,-0.033401,0.005181,0.280062,0.054254,-0.208160,0.714045,1.000000,0.047573,-0.004178,0.029788,-0.050624,-0.074146,-0.069319,-0.008765,0.156079,-0.033957
bedrooms,0.019509,0.221653,-0.021365,-0.155889,0.560627,0.024250,-0.000659,-0.026741,0.033489,0.047573,1.000000,-0.006262,0.044431,-0.011735,-0.063773,-0.014047,-0.057726,0.013688,-0.104694
dist,0.186218,-0.044725,0.014144,0.213351,-0.128488,-0.056113,0.033426,-0.164767,-0.030202,-0.004178,-0.006262,1.000000,0.558064,-0.363088,-0.242862,-0.346653,-0.467791,-0.147424,0.405878
metro_dist,0.024200,-0.061025,-0.002868,0.101981,-0.037267,-0.000722,0.043365,-0.109153,0.010441,0.029788,0.044431,0.558064,1.000000,-0.168010,-0.219587,-0.138876,-0.259654,-0.069506,0.086424
attr_index,0.084314,0.178228,-0.031458,-0.022286,0.028394,-0.026335,0.006319,0.114732,-0.025322,-0.050624,-0.011735,-0.363088,-0.168010,1.000000,0.714847,0.850229,0.544403,-0.126942,-0.052438
attr_index_norm,0.035687,0.292396,-0.006137,0.029140,-0.050487,-0.088949,-0.041412,0.093720,-0.075372,-0.074146,-0.063773,-0.242862,-0.219587,0.714847,1.000000,0.527623,0.472143,-0.221591,0.435237
rest_index,0.158729,0.134722,-0.031297,-0.022343,0.037330,-0.035060,0.007051,0.137747,-0.031929,-0.069319,-0.014047,-0.346653,-0.138876,0.850229,0.527623,1.000000,0.617970,-0.176704,-0.113163
rest_index_norm,-0.141629,0.144094,0.005711,-0.136846,0.038059,-0.018348,-0.037402,0.083999,-0.005995,-0.008765,-0.057726,-0.467791,-0.259654,0.544403,0.472143,0.617970,1.000000,-0.134731,0.023698
lng,-0.156467,-0.173833,-0.027829,-0.201709,0.146848,0.185748,0.041260,-0.088943,0.120379,0.156079,0.013688,-0.147424,-0.069506,-0.126942,-0.221591,-0.176704,-0.134731,1.000000,-0.159214
lat,0.056303,0.211805,0.023304,0.140762,-0.168265,-0.113811,-0.034058,-0.126433,-0.092502,-0.033957,-0.104694,0.405878,0.086424,-0.052438,0.435237,-0.113163,0.023698,-0.159214,1.000000

In [33]:
data_clean = data.drop(['Unnamed: 0', 'room_type', 'attr_index', 'rest_index', 'lng', 'lat'], axis=1)

In [34]:
data_clean

,realSum,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,guest_satisfaction_overall,bedrooms,dist,metro_dist,attr_index_norm,rest_index_norm,city,weekend
0,156.874664,False,True,2.0,True,1,0,10.0,95.0,1,2.978468,1.595733,6.230648,15.191486,Rome,no
1,172.772543,False,True,2.0,False,1,0,9.0,80.0,1,0.935371,0.649269,10.696887,27.249208,Rome,no
2,277.745307,False,False,4.0,False,0,1,9.0,90.0,1,2.203025,0.494697,15.328408,35.400361,Rome,no
3,444.906834,False,False,6.0,False,1,0,9.0,92.0,2,2.703010,1.295153,17.852092,44.325522,Rome,no
4,131.391298,False,True,3.0,False,1,0,9.0,91.0,1,1.295968,0.867455,7.026475,18.215634,Rome,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2622,74.051508,False,False,3.0,True,0,0,10.0,98.0,1,3.311976,1.856865,1.849891,1.062098,Athens,yes
2623,295.737351,False,False,4.0,True,0,1,10.0,100.0,1,1.800556,0.571033,5.510019,3.044796,Athens,yes
2624,169.193635,False,False,4.0,True,0,1,10.0,99.0,2,3.845100,0.786416,1.592276,0.910205,Athens,yes
2625,160.991728,False,False,4.0,True,1,0,10.0,100.0,1,4.827460,0.141952,1.345116,0.786420,Athens,yes
2626,192.393317,False,False,4.0,False,0,1,10.0,99.0,1,1.776319,0.317120,4.036300,2.228013,Athens,yes

In [35]:
data_clean['bedrooms'].value_counts()

1     36333
2      9290
0      4485
3      1477
4        96
9        10
5        10
8         2
10        2
6         2
Name: bedrooms, dtype: int64

In [36]:
data_clean = pd.get_dummies(data_clean, columns = ['room_shared', 'room_private', 'host_is_superhost', 'weekend'], drop_first =True)
data_clean

,realSum,person_capacity,multi,biz,cleanliness_rating,guest_satisfaction_overall,bedrooms,dist,metro_dist,attr_index_norm,rest_index_norm,city,room_shared_True,room_private_True,host_is_superhost_True,weekend_yes
0,156.874664,2.0,1,0,10.0,95.0,1,2.978468,1.595733,6.230648,15.191486,Rome,0,1,1,0
1,172.772543,2.0,1,0,9.0,80.0,1,0.935371,0.649269,10.696887,27.249208,Rome,0,1,0,0
2,277.745307,4.0,0,1,9.0,90.0,1,2.203025,0.494697,15.328408,35.400361,Rome,0,0,0,0
3,444.906834,6.0,1,0,9.0,92.0,2,2.703010,1.295153,17.852092,44.325522,Rome,0,0,0,0
4,131.391298,3.0,1,0,9.0,91.0,1,1.295968,0.867455,7.026475,18.215634,Rome,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2622,74.051508,3.0,0,0,10.0,98.0,1,3.311976,1.856865,1.849891,1.062098,Athens,0,0,1,1
2623,295.737351,4.0,0,1,10.0,100.0,1,1.800556,0.571033,5.510019,3.044796,Athens,0,0,1,1
2624,169.193635,4.0,0,1,10.0,99.0,2,3.845100,0.786416,1.592276,0.910205,Athens,0,0,1,1
2625,160.991728,4.0,1,0,10.0,100.0,1,4.827460,0.141952,1.345116,0.786420,Athens,0,0,1,1
2626,192.393317,4.0,0,1,10.0,99.0,1,1.776319,0.317120,4.036300,2.228013,Athens,0,0,0,1

In [37]:
data_clean[['cleanliness_rating']] = data[['cleanliness_rating']].astype(int)

In [38]:
data_clean[['realSum', 'dist', 'metro_dist']]=data_clean[['realSum', 'dist', 'metro_dist']].round(2)

In [39]:
data_clean['realSum'].describe()

count    51707.000000
mean       279.879630
std        327.948372
min         34.780000
25%        148.750000
50%        211.340000
75%        319.690000
max      18545.450000
Name: realSum, dtype: float64

In [40]:
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.preprocessing import PowerTransformer, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

import statsmodels.api as sm
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

In [41]:
RAND_STATE = 32 # for reproducible shuffling
TT_RATIO = 0.25 # test/train

In [42]:
data_clean.isna().any()

realSum                       False
person_capacity               False
multi                         False
biz                           False
cleanliness_rating            False
guest_satisfaction_overall    False
bedrooms                      False
dist                          False
metro_dist                    False
attr_index_norm               False
rest_index_norm               False
city                          False
room_shared_True              False
room_private_True             False
host_is_superhost_True        False
weekend_yes                   False
dtype: bool

In [43]:
data_clean_numerical = data_clean.drop(['city'], axis=1)

In [44]:
data_clean_numerical

,realSum,person_capacity,multi,biz,cleanliness_rating,guest_satisfaction_overall,bedrooms,dist,metro_dist,attr_index_norm,rest_index_norm,room_shared_True,room_private_True,host_is_superhost_True,weekend_yes
0,156.87,2.0,1,0,10,95.0,1,2.98,1.60,6.230648,15.191486,0,1,1,0
1,172.77,2.0,1,0,9,80.0,1,0.94,0.65,10.696887,27.249208,0,1,0,0
2,277.75,4.0,0,1,9,90.0,1,2.20,0.49,15.328408,35.400361,0,0,0,0
3,444.91,6.0,1,0,9,92.0,2,2.70,1.30,17.852092,44.325522,0,0,0,0
4,131.39,3.0,1,0,9,91.0,1,1.30,0.87,7.026475,18.215634,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2622,74.05,3.0,0,0,10,98.0,1,3.31,1.86,1.849891,1.062098,0,0,1,1
2623,295.74,4.0,0,1,10,100.0,1,1.80,0.57,5.510019,3.044796,0,0,1,1
2624,169.19,4.0,0,1,10,99.0,2,3.85,0.79,1.592276,0.910205,0,0,1,1
2625,160.99,4.0,1,0,10,100.0,1,4.83,0.14,1.345116,0.786420,0,0,1,1
2626,192.39,4.0,0,1,10,99.0,1,1.78,0.32,4.036300,2.228013,0,0,0,1

#### X-Y split

In [45]:
x = data_clean_numerical.drop('realSum', axis=1)
y = data_clean_numerical.realSum

#### Train - Test split

In [46]:
# test-train split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=TT_RATIO, random_state=RAND_STATE)
x_train = pd.DataFrame(x_train)
x_test = pd.DataFrame(x_test)
x_train.describe()

,person_capacity,multi,biz,cleanliness_rating,guest_satisfaction_overall,bedrooms,dist,metro_dist,attr_index_norm,rest_index_norm,room_shared_True,room_private_True,host_is_superhost_True,weekend_yes
count,38780.000000,38780.000000,38780.000000,38780.000000,38780.000000,38780.000000,38780.000000,38780.000000,38780.000000,38780.000000,38780.000000,38780.000000,38780.000000,38780.000000
mean,3.166039,0.292135,0.348659,9.392316,92.661578,1.159025,3.197077,0.680839,13.423504,22.735122,0.007220,0.359232,0.257143,0.508020
std,1.300033,0.454750,0.476552,0.955026,8.905833,0.629445,2.403874,0.857698,9.807319,17.799960,0.084666,0.479781,0.437064,0.499942
min,2.000000,0.000000,0.000000,2.000000,20.000000,0.000000,0.020000,0.000000,0.926301,0.592757,0.000000,0.000000,0.000000,0.000000
25%,2.000000,0.000000,0.000000,9.000000,90.000000,1.000000,1.460000,0.250000,6.376706,8.727279,0.000000,0.000000,0.000000,0.000000
50%,3.000000,0.000000,0.000000,10.000000,95.000000,1.000000,2.610000,0.410000,11.460722,17.438471,0.000000,0.000000,0.000000,1.000000
75%,4.000000,1.000000,1.000000,10.000000,99.000000,1.000000,4.270000,0.740000,17.423782,32.882718,0.000000,1.000000,1.000000,1.000000
max,6.000000,1.000000,1.000000,10.000000,100.000000,10.000000,25.280000,14.270000,100.000000,100.000000,1.000000,1.000000,1.000000,1.000000

#### Standarize the data

In [47]:
sts = StandardScaler()

x_train_standarized = sts.fit_transform(x_train)
x_test_standarized = sts.transform(x_test)

x_train_standarized = pd.DataFrame(x_train_standarized)

#### Apply linear regression.

In [48]:
x_train_const = sm.add_constant(x_train) # adding a constant

model = sm.OLS(y_train, x_train_const).fit()
predictions_train = model.predict(x_train_const)

x_test_const = sm.add_constant(x_test) # adding a constant
predictions_test = model.predict(x_test_const)
print_model = model.summary()
print(print_model)

                            OLS Regression Results
==============================================================================
Dep. Variable:                realSum   R-squared:                       0.157
Model:                            OLS   Adj. R-squared:                  0.157
Method:                 Least Squares   F-statistic:                     516.8
Date:                Mon, 06 Mar 2023   Prob (F-statistic):               0.00
Time:                        16:34:17   Log-Likelihood:            -2.7801e+05
No. Observations:               38780   AIC:                         5.560e+05
Df Residuals:                   38765   BIC:                         5.562e+05
Df Model:                          14
Covariance Type:            nonrobust
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
const                        -92.4962     20.257     -4.566      0.000    -132.200     -52.792
person_capacity               12.8812      1.740      7.402      0.000       9.470      16.292
multi                        -10.7347      4.057     -2.646      0.008     -18.686      -2.783
biz                            5.1828      4.011      1.292      0.196      -2.679      13.045
cleanliness_rating             2.3170      2.414      0.960      0.337      -2.415       7.049
guest_satisfaction_overall     0.5574      0.263      2.115      0.034       0.041       1.074
bedrooms                     101.1085      3.137     32.228      0.000      94.959     107.258
dist                          13.7722      0.899     15.315      0.000      12.010      15.535
metro_dist                   -13.4816      2.265     -5.952      0.000     -17.921      -9.042
attr_index_norm               10.3722      0.189     54.932      0.000      10.002      10.742
rest_index_norm                0.3929      0.113      3.482      0.000       0.172       0.614
room_shared_True            -165.3255     18.954     -8.722      0.000    -202.476    -128.175
room_private_True            -95.4307      4.038    -23.632      0.000    -103.346     -87.516
host_is_superhost_True       -23.0910      3.867     -5.971      0.000     -30.671     -15.511
weekend_yes                    4.8116      3.198      1.505      0.132      -1.457      11.080
==============================================================================
Omnibus:                    96511.253   Durbin-Watson:                   1.990
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       2089916686.029
Skew:                          27.000   Prob(JB):                         0.00
Kurtosis:                    1138.994   Cond. No.                     1.24e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.24e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [49]:
x_train_const = sm.add_constant(x_train_standarized.to_numpy()) # adding a constant

model = sm.OLS(y_train, x_train_const).fit()
predictions_train = model.predict(x_train_const)

x_test_const = sm.add_constant(x_test_standarized) # adding a constant
predictions_test = model.predict(x_test_const)
print_model = model.summary()
print(print_model)

                            OLS Regression Results
==============================================================================
Dep. Variable:                realSum   R-squared:                       0.157
Model:                            OLS   Adj. R-squared:                  0.157
Method:                 Least Squares   F-statistic:                     516.8
Date:                Mon, 06 Mar 2023   Prob (F-statistic):               0.00
Time:                        16:34:17   Log-Likelihood:            -2.7801e+05
No. Observations:               38780   AIC:                         5.560e+05
Df Residuals:                   38765   BIC:                         5.562e+05
Df Model:                          14
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        281.6014      1.596    176.485      0.000     278.474     284.729
x1            16.7457      2.262      7.402      0.000      12.311      21.180
x2            -4.8816      1.845     -2.646      0.008      -8.497      -1.266
x3             2.4698      1.912      1.292      0.196      -1.277       6.216
x4             2.2127      2.306      0.960      0.337      -2.306       6.732
x5             4.9638      2.347      2.115      0.034       0.365       9.563
x6            63.6414      1.975     32.228      0.000      59.771      67.512
x7            33.1063      2.162     15.315      0.000      28.869      37.343
x8           -11.5629      1.943     -5.952      0.000     -15.371      -7.755
x9           101.7220      1.852     54.932      0.000      98.092     105.352
x10            6.9943      2.009      3.482      0.000       3.057      10.931
x11          -13.9972      1.605     -8.722      0.000     -17.143     -10.852
x12          -45.7853      1.937    -23.632      0.000     -49.583     -41.988
x13          -10.0921      1.690     -5.971      0.000     -13.405      -6.779
x14            2.4055      1.599      1.505      0.132      -0.728       5.539
==============================================================================
Omnibus:                    96511.253   Durbin-Watson:                   1.990
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       2089916686.029
Skew:                          27.000   Prob(JB):                         0.00
Kurtosis:                    1138.994   Cond. No.                         2.92
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

#### Linear Regression

In [50]:
lm = LinearRegression()
model = lm.fit(x_train,y_train)
model.coef_
model.intercept_

-92.496230775181

In [51]:
model.score(x_train, y_train)

0.15728793888117643

In [52]:
y_pred = pd.DataFrame(model.predict(x_test),columns = ['realSum'] )      # model prediction
y_pred_train =  pd.DataFrame(model.predict(x_train),columns = ['realSum'])

In [53]:
mse(y_test,y_pred)

59109.4767742999

In [54]:
rmse = np.sqrt(mse(y_test,y_pred))
rmse

243.1244059618448

In [55]:
##prediction on the train set
mse(y_train,y_pred_train)

98695.02813413141

In [56]:
mae(y_test,y_pred)

110.95214018042999

In [57]:
R2=r2_score(y_test,y_pred)
R2

0.2499703700146465

In [58]:
R2_test=model.score(x_test,y_test)
R2_train=model.score(x_train,y_train)
Adj_R2= 1 - (1-R2)*(len(y_test)-1)/(len(y_test)-x_test.shape[1]-1)
Adj_R2

0.2491571408619362

In [59]:
from sklearn.linear_model import Lasso,Ridge,ElasticNet, LinearRegression
model_lasso=Lasso(alpha=0.05)

model_lasso.fit(x_train, y_train)
print(f"{model_lasso.__class__.__name__}: Train -> {model_lasso.score(x_train, y_train)}, Test -> {model_lasso.score(x_test, y_test)}")

Lasso: Train -> 0.15728420752986372, Test -> 0.24996466041462884

In [60]:
model_ridge=Ridge(alpha=1000)
model_ridge.fit(x_train, y_train)
print(f"{model_ridge.__class__.__name__}: Train -> {model_ridge.score(x_train, y_train)}, Test -> {model_ridge.score(x_test, y_test)}")

Ridge: Train -> 0.1558100867073915, Test -> 0.2478354987116873

#### KNN model

In [61]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings('ignore')

In [62]:
model = DecisionTreeRegressor()
model.fit(x_train, y_train)

print("X_train has %d rows and %d columns"  %(x_train.shape[0],x_train.shape[1]))
print("-----------------------------------")
print("The coefficient of determination for the test data is R2=%.2f"
      %(model.score(x_test, y_test)))
print("The coefficient of determination for the train data is R2=%.2f"
      %(model.score(x_train, y_train)))

X_train has 38780 rows and 14 columns
-----------------------------------
The coefficient of determination for the test data is R2=-0.88
The coefficient of determination for the train data is R2=1.00

In [63]:
scores=cross_val_score(model, x_train, y_train, cv=5)
print("Cross validation scores: ", scores)
print("Score stats: %0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

Cross validation scores:  [ 0.34228627 -0.04264303 -0.09774109  0.29758735 -0.05705706]
Score stats: 0.09 accuracy with a standard deviation of 0.19

In [64]:
model1 = DecisionTreeRegressor()
model2 = LinearRegression()
model3 = KNeighborsRegressor()

model_pipeline = [model1, model2, model3]
model_names = ['Regression Tree', 'Linear Regression', 'KNN']
scores = {}
i=0
for model in model_pipeline:
    mean_score = np.mean(cross_val_score(model, x_train, y_train, cv=5))
    scores[model_names[i]] = mean_score
    i = i+1
print(scores)

{'Regression Tree': 0.023564612331999933, 'Linear Regression': 0.16538633928889246, 'KNN': 0.1703267183356078}

#### split cities

In [65]:
def split_cities(cities):
    data_cities = data_clean[data_clean['city'] == cities]
    data_cities = data_cities.drop(['city'], axis=1)
    return data_cities

In [66]:
data_berlin = split_cities('Berlin')
data_berlin.columns

Index(['realSum', 'person_capacity', 'multi', 'biz', 'cleanliness_rating',
       'guest_satisfaction_overall', 'bedrooms', 'dist', 'metro_dist',
       'attr_index_norm', 'rest_index_norm', 'room_shared_True',
       'room_private_True', 'host_is_superhost_True', 'weekend_yes'],
      dtype='object')

In [67]:
data_berlin.to_csv("data_berlin.csv")

In [68]:
data_amsterdam = split_cities('Amsterdam')

In [69]:
data_amsterdam.to_csv('data_amsterdam.csv')

In [70]:
data_paris = split_cities('Paris')

In [71]:
data_paris.to_csv('data_paris.csv')

In [72]:
data_rome = split_cities('Rome')

In [73]:
data_rome.to_csv('data_rome.csv')

In [79]:
data_lisbon = split_cities('Lisbon')

In [80]:
data_lisbon.to_csv('data_lisbon.csv')

In [81]:
data_london = split_cities('London')
data_london.to_csv('data_london.csv')

In [82]:
data_barcelona = split_cities('Barcelona')
data_barcelona.to_csv('data_barcelona.csv')

In [83]:
data_athens = split_cities('Athens')
data_athens.to_csv('data_athens.csv')

In [84]:
data_budapest = split_cities('Budapest')
data_budapest.to_csv('data_budapest.csv')

In [87]:
data_vienna = split_cities('Vienna')
data_vienna.to_csv('data_vienna.csv')

In [ ]:
# berlin, paris, rome, lisboa, londres, amsterdam(pocas observaciones), barcelona (), athens